# Claude-written DRAFT Juba Arabic, vocabulary corrected against Smith & Ama (1985) A Dictionary of Juba Arabic & English for: moya (water), feyadaan (flood), yabis (dry), hamilaan (pregnant), kesilu (wash), sharaab (drinking), namusiiya (mosquito net), radiyoo, musteeshfa (hospital), sulta (authority), salatiin (chiefs), jiaan (hungry), iyaal (children) (Latin letters). No native-speaker check. Used only by load_claude_drafts.py.
D = {
'title.national': "Kalam ta indar badri ta usbu: Sudan Janub",
'title.area': "Kalam ta indar badri ta usbu: {area}",
'week_line': "Usbu ta {date}. Data ta matara ma turab lissa {data_end}; tawaqu' kalam fi {run}.",
'audience': "Da kalam ligi jamaa, salatiin, zurra, rua ta hayawan, sulta ta mahali ma sharikat fi {area}. Min fadlak wadi kalam da ligi jamaa ta ita ma radiyoo ta mahali.",
'summary.some': "Fi {area}, {n_alert} min {n_total} county indu indar usbu da: {n_red} ahmar, {n_orange} burtukali ma {n_yellow} asfar.",
'summary.none': "Ma fi county fi {area} indu indar usbu da. Utur kwaisi tuqs ma bahar, ma simi radiyoo.",
'flood_now': "Khatar ta feyadaan wala moya tagil: {counties}.",
'dry_now': "Khatar ta yabis: {counties}.",
'river_now': "Mizan ta bahar fi daraja ta isti'dad wala tafil garib: {counties}.",
'less_rain_note': "Indar ta yabis yaani matara kalil min adi. Da ma yaani matara ma fi.",
'hdr.situation': "Shunu da hasal",
'hdr.todo': "Jamaa lazim yisawi shunu?",
'hdr.impact': "Shunu mumkin yihsal",
'hdr.action': "Shunu lazim yisawi",
'hdr.news': "Akhbar jadid (yom 21 ta khalas, ligi Ingilizi)",
'hdr.outlook': "Tawaqu' ta mausim",
'col.county': "County", 'col.level': "Indar", 'col.hazard': "Khatar", 'col.rain': "Matara usbu da (mm)", 'col.heavy': "Ihtimal ta matara kebir",
'lvl.red': "ahmar", 'lvl.orange': "burtukali", 'lvl.yellow': "asfar", 'lvl.green': "akhdar",
'hz.flood': "feyadaan", 'hz.dry': "yabis",
'outlook.rain.below': "Tawaqu' ta mausim ({season}): matara kalil min adi aktar ihtimal fi {areas}.",
'outlook.rain.near': "Tawaqu' ta mausim ({season}): matara adi aktar ihtimal fi {areas}.",
'outlook.rain.above': "Tawaqu' ta mausim ({season}): matara aktar min adi aktar ihtimal fi {areas}.",
'outlook.temp.above': "Tawaqu' ta mausim ({season}): har aktar min adi aktar ihtimal fi {areas}.",
'outlook.temp.near': "Tawaqu' ta mausim ({season}): har adi aktar ihtimal fi {areas}.",
'outlook.temp.below': "Tawaqu' ta mausim ({season}): bard aktar min adi aktar ihtimal fi {areas}.",
'disclaimer': "Indar rasmi bijiyi min Khidma ta Tuqs ta Sudan Janub (SSMS). Kalam da musa'ada ligi garar min manassa ta tuqs ma moya (matara min satellite, turab, mizan ta bahar ma tawaqu' ta ECMWF).",
'source_line': "Masdar: {source}.",
'sector.health': "Siha", 'sector.agriculture': "Zira'a", 'sector.livestock': "Hayawan", 'sector.water': "Moya", 'sector.community': "Jamaa ma tahaddur ligi khatar",
'hz_title.flood': "Matara kebir ma feyadaan", 'hz_title.dry': "Yabis", 'hz_title.heat': "Har",
'flood.health.impact.1': "Moya ta feyadaan mumkin yiwasikh moya ta sharaab.",
'flood.health.impact.2': "Maradh kida kolera ma malaria mumkin yinta'ashar.",
'flood.health.impact.3': "Sel mumkin yikharib musteeshfa ma yaqta' tarik ligi.",
'flood.health.impact.4': "Kan bet, mal wala ahal wa'a, da mumkin yijib hamm ma ta'ab.",
'flood.health.action.1': "Ghali wala 'alij moya ta sharaab.",
'flood.health.action.2': "Nam fi namusiiya indu dawa.",
'flood.health.action.3': "Ma mashi wala la'ab fi moya ta feyadaan, ma kesilu id ma sabun.",
'flood.health.action.4': "Rudu ligi ard 'ali kan indar ta feyadaan bijiyi.",
'flood.health.action.5': "Sharikat ta siha: hut dawa muhim awwal fi mukan amin ma fi wasat.",
'flood.health.action.6': "Darrib amil siha ta Boma ma mutawwi'in ligi istijaba ta tawari ma kontrol ta maradh.",
'flood.agriculture.impact.1': "Zara' mumkin yimshi ma moya wala yifsid fi marah ta zira'a indu moya.",
'flood.agriculture.impact.2': "Zira'a ma hashish mumkin yiakhir.",
'flood.agriculture.impact.3': "Bizir ma akil ta makhzan mumkin yikharib.",
'flood.agriculture.action.1': "Sawi wala asluh sidd badri.",
'flood.agriculture.action.2': "Hut bizir ma akil ligi fog ma yabis.",
'flood.agriculture.action.3': "Ligi marah ta zira'a bijiyi moya, zara' ta tiqdar ma turab ratib, misl uruz.",
'flood.agriculture.action.4': "Hut akil ma ashya ta ghayr akil awwal ligi usar mumkin yitatharu.",
'flood.livestock.impact.1': "Maradh ta moya mumkin yinta'ashar fi hayawan.",
'flood.livestock.impact.2': "Marah ta rai ma zariba ta bagar mumkin tighara, ma hayawan mumkin yibaqa hasur.",
'flood.livestock.action.1': "Shil hayawan ligi ard 'ali badri, ma jiran ta ita.",
'flood.livestock.action.2': "Ta'ish hayawan ta dawa gabl feyadaan.",
'flood.livestock.action.3': "Hut ihtiyat ta alaf.",
'flood.water.impact.1': "Mizan ta bahar ma jari ta moya yitla'a.",
'flood.water.impact.2': "Moya ta feyadaan mumkin yiwasikh bir, pompa ta id ma moya maftuh.",
'flood.water.action.1': "Utur mizan ta bahar yitla'a, ma qul sulta ta mahali ligi khatar.",
'flood.water.action.2': "Himi mahal ta moya min feyadaan, ma ghali moya gabl sharaab.",
'flood.water.action.3': "Lim moya ta matara fi inaa nadif.",
'flood.community.impact.1': "Tarik ma kubri mumkin yiquta', ma usar mumkin yikharuju min bet.",
'flood.community.impact.2': "Tawattur mumkin yitla' kan usar kutir yishtarik ard 'ali kalil.",
'flood.community.action.1': "Ittifag min dilwakti ligi ard 'ali ma tarik ta harab ligi nas, hayawan ma akil.",
'flood.community.action.2': "Hut markab jahiz, ma tabi' shaikh ta ita, sulta ta mahali ma radiyoo.",
'flood.community.action.3': "Sawi jalsa ta tawiya ta jamaa ma lijan ta idara ta khatar (DRMC).",
'flood.community.action.4': "Darrib jamaa ligi tahaddur ma istijaba.",
'flood.community.action.5': "Shariku ard 'ali bi salam, ma utur iyaal, ajuz ma nas indu ajz awwal.",
'dry.health.impact.1': "Akil ma laban kalil mumkin yijib suu' taghdiya.",
'dry.health.impact.2': "Turab ta ghubar mumkin yijib mushkila ta nafas.",
'dry.health.impact.3': "Moya kalil ma kesilu id kalil mumkin yinashir maradh.",
'dry.health.action.1': "Hut ma himi moya nadif.",
'dry.health.action.2': "Kesilu id ma sabun kullu wakit moya mawjud.",
'dry.health.action.3': "Shariku kalam ta siha fi radiyoo ta jamaa ma fi tawasul ta khatar ma ishtirak ta jamaa (RCCE).",
'dry.agriculture.impact.1': "Zira'a mumkin yiakhir, ma zara' badri mumkin yifsid.",
'dry.agriculture.impact.2': "Hasad ma marah ta zira'a mumkin yinqus.",
'dry.agriculture.impact.3': "Hashara ma maradh ta zara' mumkin yizid, ma taklifa ta intaj mumkin tizid.",
'dry.agriculture.impact.4': "Nuqs ta akil ma suu' taghdiya mumkin yijiyi.",
'dry.agriculture.action.1': "Akhir zira'a lissa turab yibaqa ratib kifaya.",
'dry.agriculture.action.2': "Istaghdim zara' ta tiqdar yabis ma bizir ta nudj sari'.",
'dry.agriculture.action.3': "Lim ma wafir moya, ma istaghdim ri bi tanqit kan mumkin.",
'dry.agriculture.action.4': "Sawi shughul kutir ma hut ihtiyat ta akil.",
'dry.livestock.impact.1': "Rai ma moya mumkin yinqus, ma hayawan mumkin yida'if fi har.",
'dry.livestock.impact.2': "Rua ma hayawan mumkin yimshi bi'id ligi moya ma rai.",
'dry.livestock.impact.3': "Laban ma lahm mumkin yinqus, ma maradh ta hayawan mumkin yinta'ashar.",
'dry.livestock.action.1': "Ta'ish ma ghayyir dud ta hayawan.",
'dry.livestock.action.2': "Hut hayawan fi zil, ma ita'am ma sagi moya.",
'dry.livestock.action.3': "Kharrit mashi ta rai badri, ma ittifag bi salam ma jama'a ta jiran ligi tarik ma mahal ta moya.",
'dry.water.impact.1': "Moya ta bahar ma mizan yinqus, ma moya aktar yitbakhar.",
'dry.water.impact.2': "Moya kalil yidkhul fi turab ligi yimla bir ma bir ta pompa.",
'dry.water.action.1': "Istaghdim moya bi hizr ma khazin.",
'dry.water.action.2': "Lim moya ta matara kullu wakit bijiyi.",
'dry.water.action.3': "Istaghdim bir ma pompa ta id, ma himi min kharab.",
'dry.community.impact.1': "Hasad ratib ma moya kalil mumkin yijib jiaan ma mawt ta hayawan.",
'dry.community.impact.2': "Khilaf ligi moya ma rai, ma fi zariba ta bagar, mumkin yizid.",
'dry.community.action.1': "Khazin akil, ma ghayr safar tawil fi har.",
'dry.community.action.2': "Kun fi zil, ma sharaab moya amin kifaya: taqriban 4 ligi 8 litr fi yom, hasab ma mawjud.",
'dry.community.action.3': "Hall khilaf ta moya ma rai bi salatiin ma qadat ta mahali.",
'heat.health.impact.1': "Har mumkin yijib yabis ta jism, ta'ab ta har ma darba ta shams.",
'heat.health.impact.2': "Iyaal, ajuz ma nisa hamilaan fi khatar aktar.",
'heat.health.action.1': "Ashrabu moya amin kifaya: taqriban 4 ligi 8 litr fi yom, hasab ma mawjud.",
'heat.health.action.2': "Ma gif fi shams mubashir, ma libis tiyab khafif ma wasi'.",
'heat.health.action.3': "Qalil sa'at ta shughul fi har ta nus ta nahar.",
'heat.livestock.impact.1': "Hayawan yuta'ab min har ma ya'ti laban ma lahm kalil.",
'heat.livestock.action.1': "Hut hayawan fi zil ma sagi moya.",
'heat.community.impact.1': "Mahal ta moya yiyabis sari'a, ma harig ta ghaba mumkin yizid.",
'heat.community.action.1': "Sawi khat ta mani' ta nar hawl qura ma marah ta zira'a.",
'heat.community.action.2': "Qalil safar tawil ta nas ma hayawan.",
}
